CREATE INDEX "customers_phone_idx" ON "customers" USING btree ("phone");--> statement-breakpoint
CREATE INDEX "customers_company_idx" ON "customers" USING btree ("company");--> statement-breakpoint
CREATE INDEX "customers_created_at_idx" ON "customers" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "customers_active_orders_idx" ON "customers" USING btree ("active_orders_count");--> statement-breakpoint
CREATE INDEX "inventory_items_category_idx" ON "inventory_items" USING btree ("category");--> statement-breakpoint
CREATE INDEX "inventory_items_category_counter_idx" ON "inventory_items" USING btree ("category_counter");--> statement-breakpoint
CREATE INDEX "inventory_items_category_counter_composite_idx" ON "inventory_items" USING btree ("category","category_counter");--> statement-breakpoint
CREATE INDEX "inventory_items_created_at_idx" ON "inventory_items" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "inventory_sizes_item_id_idx" ON "inventory_sizes" USING btree ("item_id");--> statement-breakpoint
CREATE INDEX "inventory_tags_item_id_idx" ON "inventory_tags" USING btree ("item_id");--> statement-breakpoint
CREATE INDEX "inventory_tags_tag_id_idx" ON "inventory_tags" USING btree ("tag_id");--> statement-breakpoint
CREATE INDEX "inventory_tags_item_tag_idx" ON "inventory_tags" USING btree ("item_id","tag_id");--> statement-breakpoint
CREATE INDEX "order_items_order_id_idx" ON "order_items" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "order_items_inventory_item_id_idx" ON "order_items" USING btree ("inventory_item_id");--> statement-breakpoint
CREATE INDEX "order_items_is_custom_idx" ON "order_items" USING btree ("is_custom");--> statement-breakpoint
CREATE INDEX "order_items_is_extension_idx" ON "order_items" USING btree ("is_extension");--> statement-breakpoint
CREATE INDEX "order_notes_order_id_idx" ON "order_notes" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "order_notes_item_id_idx" ON "order_notes" USING btree ("item_id");--> statement-breakpoint
CREATE INDEX "order_notes_done_idx" ON "order_notes" USING btree ("done");--> statement-breakpoint
CREATE INDEX "orders_customer_id_idx" ON "orders" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "orders_order_date_idx" ON "orders" USING btree ("order_date");--> statement-breakpoint
CREATE INDEX "orders_expected_return_date_idx" ON "orders" USING btree ("expected_return_date");--> statement-breakpoint
CREATE INDEX "orders_status_idx" ON "orders" USING btree ("status");--> statement-breakpoint
CREATE INDEX "orders_payment_status_idx" ON "orders" USING btree ("payment_status");--> statement-breakpoint
CREATE INDEX "orders_customer_status_idx" ON "orders" USING btree ("customer_id","status");--> statement-breakpoint
CREATE INDEX "orders_customer_payment_status_idx" ON "orders" USING btree ("customer_id","payment_status");--> statement-breakpoint
CREATE INDEX "orders_created_at_idx" ON "orders" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "orders_document_status_idx" ON "orders" USING btree ("document_status");--> statement-breakpoint
CREATE INDEX "users_employee_key_idx" ON "users" USING btree ("employee_key");--> statement-breakpoint
CREATE INDEX "users_status_idx" ON "users" USING btree ("status");--> statement-breakpoint
CREATE INDEX "users_created_at_idx" ON "users" USING btree ("created_at");